### ISSUE TITLE
Terjira fails to run

### ISSUE THREAD

**Issue by garwil** [anatol/quarry#108]
Thanks for accepting my PR to add Terjira. However, I get the following error message on running it.

```
Traceback (most recent call last):
	39: from /usr/bin/jira:23:in `<main>'
	38: from /usr/bin/jira:23:in `load'
	37: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/bin/jira:5:in `<top (required)>'
	36: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	35: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	34: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/lib/terjira.rb:5:in `<top (required)>'
	33: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/lib/terjira.rb:5:in `each'
	32: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/lib/terjira.rb:5:in `block in <top (required)>'
	31: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	30: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	29: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/lib/terjira/base_cli.rb:4:in `<top (required)>'
	28: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/lib/terjira/base_cli.rb:4:in `each'
	27: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/lib/terjira/base_cli.rb:4:in `block in <top (required)>'
	26: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	25: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	24: from /usr/lib/ruby/gems/2.6.0/gems/terjira-0.4.3/lib/terjira/presenters/common_presenter.rb:3:in `<top (required)>'
	23: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	22: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	21: from /usr/lib/ruby/gems/2.6.0/gems/tty-table-0.10.0/lib/tty-table.rb:4:in `<top (required)>'
	20: from /usr/lib/ruby/gems/2.6.0/gems/tty-table-0.10.0/lib/tty-table.rb:4:in `require_relative'
	19: from /usr/lib/ruby/gems/2.6.0/gems/tty-table-0.10.0/lib/tty/table.rb:8:in `<top (required)>'
	18: from /usr/lib/ruby/gems/2.6.0/gems/tty-table-0.10.0/lib/tty/table.rb:8:in `require_relative'
	17: from /usr/lib/ruby/gems/2.6.0/gems/tty-table-0.10.0/lib/tty/table/header.rb:6:in `<top (required)>'
	16: from /usr/lib/ruby/gems/2.6.0/gems/tty-table-0.10.0/lib/tty/table/header.rb:6:in `require_relative'
	15: from /usr/lib/ruby/gems/2.6.0/gems/tty-table-0.10.0/lib/tty/table/field.rb:5:in `<top (required)>'
	14: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /usr/lib/ruby/gems/2.6.0/gems/strings-0.1.5/lib/strings.rb:8:in `<top (required)>'
	11: from /usr/lib/ruby/gems/2.6.0/gems/strings-0.1.5/lib/strings.rb:8:in `require_relative'
	10: from /usr/lib/ruby/gems/2.6.0/gems/strings-0.1.5/lib/strings/truncate.rb:5:in `<top (required)>'
	 9: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/each_grapheme.rb:5:in `<top (required)>'
	 6: from /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/each_grapheme.rb:10:in `<module:UnicodeUtils>'
	 5: from /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/read_cdata.rb:119:in `read_hexdigit_map'
	 4: from /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/read_cdata.rb:119:in `tap'
	 3: from /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/read_cdata.rb:120:in `block in read_hexdigit_map'
	 2: from /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/read_cdata.rb:28:in `open_cdata_file'
	 1: from /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/read_cdata.rb:28:in `open'
/usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/lib/unicode_utils/read_cdata.rb:28:in `initialize': No such file or directory @ rb_sysopen - /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0/cdata/grapheme_break_property (Errno::ENOENT)
```

If I install the `unicode_utils` gem via `gem install`, Terjira works as expected.

I've done a diff of the two directories:

```
diff -qr /usr/lib/ruby/gems/2.6.0/gems/unicode_utils-1.4.0 ~/.gem/ruby/2.6.0/gems/unicode_utils-1.4.0/
Only in /home/xxxxxx/.gem/ruby/2.6.0/gems/unicode_utils-1.4.0/: CHANGES.txt
Only in /home/xxxxxx/.gem/ruby/2.6.0/gems/unicode_utils-1.4.0/: INSTALL.txt
Only in /home/xxxxxx/.gem/ruby/2.6.0/gems/unicode_utils-1.4.0/: LICENSE.txt
Only in /home/xxxxxx/.gem/ruby/2.6.0/gems/unicode_utils-1.4.0/: README.rdoc
Only in /home/xxxxxx/.gem/ruby/2.6.0/gems/unicode_utils-1.4.0/: cdata
Only in /home/xxxxxx/.gem/ruby/2.6.0/gems/unicode_utils-1.4.0/: test
```

**Comment by anatol** [comment]
Thank you for your report. This issue should be fixed now. Could you please check that `terjira` works as expected?

**Comment by garwil** [comment]
That works perfectly now, thanks for taking the time to fix it!
