### ISSUE TITLE
rebuild for ruby 2.7.0 needed?

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#114]
It looks, like I have (with up-to-date packages from arch linux and quarry) gems installed for ruby 2.6.0 and 2.7.0 in parallel:
```
$ pacman -Qo /usr/lib/ruby/gems/*
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-charlock_holmes 0.7.7-2
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-erubis 2.7.0-7
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-gemojione-3 3.3.0-1
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-github-markup-1 1.7.0-2
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-gitlab-grit 2.8.2-3
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-gollum 4.1.4-3
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-gollum-grit_adapter-1 1.0.1-4
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-gollum-lib 4.2.10-3
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-kramdown-1.9 1.9.0-3
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-mustache-0 0.99.8-4
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-nokogiri 1.10.3-1
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-posix-spawn 0.3.13-3
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-rack-1 1.6.11-2
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-rack-protection-1 1.5.5-2
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-rouge-2 2.2.1-3
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-sanitize-2 2.1.1-2
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-sinatra-1 1.4.8-3
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-stringex 2.8.5-2
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-twitter-text-1 1.14.7-2
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-unf 0.1.4-6
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-unf_ext 0.0.7.6-1
/usr/lib/ruby/gems/2.6.0/ is owned by ruby-useragent 0.16.10-2
/usr/lib/ruby/gems/2.7.0/ is owned by ruby 2.7.0-1
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-diff-lcs 1.3-4
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-json 2.3.0-2
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-mime-types 3.3.1-1
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-mime-types-data 3.2019.1009-1
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-mini_portile2 2.4.0-4
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-rack 2.0.8-1
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-rdoc 6.2.0-2
/usr/lib/ruby/gems/2.7.0/ is owned by ruby-tilt 2.0.8-4
```
The symptom is, that gollum won't start, because it claims, the gem cannot be found:
```
 Started Gollum Wiki Server.
 /usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem gollum (>= 0.a) with executable gollum (Gem::GemNotFoundException)
         from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
         from /usr/bin/gollum:23:in `<main>'
 gollum.service: Main process exited, code=exited, status=1/FAILURE
 gollum.service: Failed with result 'exit-code'.
```
This probably means, all the gems need to be rebuilt for ruby 2.7.0 ?

**Comment by anatol** [comment]
It seems you did not update `quarry` repo completely. For example current version of `ruby-charlock_holmes` is `0.7.7-3`:

```
$  pacman -Si ruby-charlock_holmes
Repository      : quarry
Name            : ruby-charlock_holmes
Version         : 0.7.7-3
Description     : Character encoding detection, brought to you by ICU
Architecture    : x86_64
URL             : https://github.com/brianmario/charlock_holmes
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : icu  ruby
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 11.81 KiB
Installed Size  : 27.38 KiB
Packager        : Anatol Pomozov <anatol.pomozov@gmail.com>
Build Date      : Tue 07 Jan 2020 02:38:06 PM PST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Comment by deep-42-thought** [comment]
of course, how can I be so stupid: I have (accidentally) removed [quarry] from my pacman.conf - sry for the noise.
