### ISSUE TITLE
ruby-asciidoctor-pdf: dependency issue: Could not find 'rexml' (~> 3.2)

### ISSUE THREAD

**Issue by TheDcoder** [anatol/quarry#124]
Looks like there is a dependency issue with `asciidoctor-pdf`:
```
TheDcoder@arch /tmp [1]> asciidoctor-pdf
/usr/lib/ruby/3.0.0/rubygems/specification.rb:1401:in `rescue in block in activate_dependencies': Could not find 'rexml' (~> 3.2) among 162 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/TheDcoder/.gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' at: /usr/lib/ruby/gems/3.0.0/specifications/prawn-svg-0.32.0.gemspec, execute `gem env` for more information
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1398:in `block in activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `each'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1369:in `activate'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `each'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1369:in `activate'
	from /usr/lib/ruby/3.0.0/rubygems.rb:286:in `block in activate_bin_path'
	from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `synchronize'
	from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `activate_bin_path'
	from /usr/bin/asciidoctor-pdf:23:in `<main>'
/usr/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'rexml' (~> 3.2) among 162 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/TheDcoder/.gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' , execute `gem env` for more information
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1399:in `block in activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `each'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1369:in `activate'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `each'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1387:in `activate_dependencies'
	from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1369:in `activate'
	from /usr/lib/ruby/3.0.0/rubygems.rb:286:in `block in activate_bin_path'
	from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `synchronize'
	from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `activate_bin_path'
	from /usr/bin/asciidoctor-pdf:23:in `<main>'
TheDcoder@arch /tmp [1]> pacman -Q ruby-asciidoctor-pdf
ruby-asciidoctor-pdf 1.6.1-1
```

Please fix it :)

**Comment by anatol** [comment]
thanks for reporting it. Could you please check if installing `ruby-rexml` fixes your issue?

**Comment by TheDcoder** [comment]
It's already installed... :confused:
```
> pacman -Q ruby-rexml
ruby-rexml 3.2.5-1
```

**Comment by anatol** [comment]
There was a problem with `prawn-icon` gem. It was fixed with https://github.com/anatol/quarry/commit/523ad507cc05fe872f95620ac9216738c77ad8c7 and with it `asciidoctor-pdf` works for me correctly:

```
asciidoctor-pdf
Usage: asciidoctor [OPTION]... FILE...
Convert the AsciiDoc input FILE(s) to the backend output format (e.g., HTML 5, DocBook 5, etc.)
Unless specified otherwise, the output is written to a file whose name is derived from the input file.
Application log messages are printed to STDERR.
Example: asciidoctor input.adoc

    -b, --backend BACKEND            set backend output format: [html5, xhtml5, docbook5, manpage] (default: html5)
                                     additional backends are supported via extended converters (e.g., pdf, epub3)
    -d, --doctype DOCTYPE            document type to use when converting document: [article, book, manpage, inline] (default: article)
    -e, --embedded                   suppress enclosing document structure and output an embedded document (default: false)
    -o, --out-file FILE              output file (default: based on path of input file); use - to output to STDOUT
        --safe                       set safe mode level to safe (default: unsafe)
                                     enables include directives, but prevents access to ancestor paths of source file
                                     provided for compatibility with the asciidoc command
    -S, --safe-mode SAFE_MODE        set safe mode level explicitly: [unsafe, safe, server, secure] (default: unsafe)
                                     disables potentially dangerous macros in source files, such as include::[]
    -s, --no-header-footer           suppress enclosing document structure and output an embedded document (default: false)
    -n, --section-numbers            auto-number section titles in the HTML backend; disabled by default
        --eruby ERUBY                specify eRuby implementation to use when rendering custom ERB templates: [erb, erubi, erubis] (default: erb)
    -a, --attribute name[=value]     a document attribute to set in the form of name, name!, or name=value pair
                                     this attribute takes precedence over the same attribute defined in the source document
                                     unless either the name or value ends in @ (i.e., name@=value or name=value@)
    -T, --template-dir DIR           a directory containing custom converter templates that override the built-in converter (requires tilt gem)
                                     may be specified multiple times
```

**Comment by TheDcoder** [comment]
Nice! Approximately when will the repository rebuild the faulty package?

**Comment by anatol** [comment]
It is already in the repo.
