### ISSUE TITLE
Compass doesn't work

### ISSUE THREAD

**Issue by daurnimator** [anatol/quarry#25]
Running compass (package `ruby-compass`) results in an error
```
$ compass
/usr/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/core/version.rb:10:in `read': No such file or directory @ rb_sysopen - /usr/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/VERSION (Errno::ENOENT)
	from /usr/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/core/version.rb:10:in `<module:Core>'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/core/version.rb:4:in `<module:Compass>'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/core/version.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/core.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass.rb:14:in `block in <top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass.rb:13:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass.rb:13:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-1.0.3/bin/compass:20:in `block in <top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-1.0.3/bin/compass:8:in `fallback_load_path'
	from /usr/lib/ruby/gems/2.2.0/gems/compass-1.0.3/bin/compass:19:in `<top (required)>'
	from /usr/bin/compass:23:in `load'
	from /usr/bin/compass:23:in `<main>'
```

Installing it via 'gem install compass' works fine

**Comment by anatol** [comment]
Just pushed updated gems to the server. Please check that 'compass' works as expected.

**Comment by daurnimator** [comment]
No error on running 'compass' anymore :)
Thanks!

**Comment by daurnimator** [comment]
Actually, I'm still having some issues.

    File to import not found or unreadable: compass/css3.

**Comment by anatol** [comment]
How do you reproduce that error?

**Comment by daurnimator** [comment]
> How do you reproduce that error?

I'm not completely sure, I'm just running a (private) build script. I managed to replicate.. I think:

```
$ mkdir -p test/sass
$ cd test
$ echo "@import 'compass/css3'" > sass/example.scss
$ compass compile sass
$ compass compile sass/example.scss 
directory stylesheets
    error sass/example.scss (Line 1: File to import not found or unreadable: compass/css3.
Load paths:
  /home/daurnimator/test/sass
  Compass::SpriteImporter)
Compilation failed in 1 files.
```

**Comment by anatol** [comment]
Just pushed another revision of this gem. Please update the package and let me know if the problem still exists.

**Comment by daurnimator** [comment]
That works.
Thankyou :)
