### ISSUE TITLE
ruby-heroku fails to run

### ISSUE THREAD

**Issue by hobarrera** [anatol/quarry#45]
This looks like a packaging error, but I'm not entirely sure how to fix it:

```
$ heroku run rails s --app my-test-app
heroku-cli: Installing Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory @ rb_sysopen - /usr/lib/ruby/gems/2.3.0/gems/heroku-3.42.44/data/cacert.pem (Errno::ENOENT)
    Command:     heroku run rails s --app shipnow-staging-notifications
    Version:     heroku-gem/3.42.44 (x86_64-linux) ruby/2.3.0
    Error ID:    3d56ded197ba4fd1ab2beedc5f74b38d


    More information in /home/hugo/.heroku/error.log

$ cat /home/hugo/.heroku/error.log
Heroku client internal error.
No such file or directory @ rb_sysopen - /usr/lib/ruby/gems/2.3.0/gems/heroku-3.42.44/data/cacert.pem
/usr/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize'
/usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
/usr/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
/usr/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
/usr/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
/usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
/usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
/usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
/usr/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
/usr/lib/ruby/gems/2.3.0/gems/heroku-3.42.44/lib/heroku/jsplugin.rb:160:in `copy_ca_cert'
/usr/lib/ruby/gems/2.3.0/gems/heroku-3.42.44/lib/heroku/jsplugin.rb:134:in `setup'
/usr/lib/ruby/gems/2.3.0/gems/heroku-3.42.44/lib/heroku/cli.rb:27:in `start'
/usr/lib/ruby/gems/2.3.0/gems/heroku-3.42.44/bin/heroku:24:in `<top (required)>'
/usr/bin/heroku:23:in `load'
/usr/bin/heroku:23:in `<main>'
```

**Comment by anatol** [comment]
Should be fixed now

**Comment by hobarrera** [comment]
Thanks!
