### ISSUE TITLE
Gollum can't open libicuuc.so.58

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#75]
It seems, gollum is compiled against the wrong version of libicuuc.so - current is libicuuc.so.59:

```
Jul 31 19:59:25 nlopc43 gollum[13796]: /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': libicuuc.so.58: cannot open shared object file: No such file or directory - /usr/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes/charlock
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.3/lib/charlock_holmes.rb:1:in `<top (required)>'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/gems/2.4.0/gems/gitlab-grit-2.8.1/lib/grit.rb:79:in `<top (required)>'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter/git_layer_grit.rb:3:in `<top (required)>'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter.rb:1:in `<top (required)>'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-lib-4.2.7/lib/gollum-lib.rb:13:in `<top (required)>'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-4.1.1/lib/gollum/app.rb:4:in `<top (required)>'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-4.1.1/bin/gollum:242:in `<top (required)>'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/bin/gollum:22:in `load'
Jul 31 19:59:25 nlopc43 gollum[13796]:         from /usr/bin/gollum:22:in `<main>'
```

... or is it `charlock-holmes`?

Could you please recompile?
Cheers, deep42thought

**Comment by anatol** [comment]
It was a problem with `charlock-holmes` and it had been recompiled.
