### ISSUE TITLE
gollum (?) needs a rebuild due to icu update

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#79]
```
Nov 27 11:42:54 jeti100 systemd[1]: Started Gollum Wiki Server.
Nov 27 11:42:54 jeti100 gollum[40843]: /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': libicuuc.so.59: cannot open shared object file: No suc
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/gems/2.4.0/gems/charlock_holmes-0.7.5/lib/charlock_holmes.rb:1:in `<top (required)>'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/gems/2.4.0/gems/gitlab-grit-2.8.2/lib/grit.rb:79:in `<top (required)>'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter/git_layer_grit.rb:3:in `<top (required)>'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter.rb:1:in `<top (required)>'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-lib-4.2.7/lib/gollum-lib.rb:13:in `<top (required)>'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-4.1.2/lib/gollum/app.rb:4:in `<top (required)>'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/lib/ruby/gems/2.4.0/gems/gollum-4.1.2/bin/gollum:242:in `<top (required)>'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/bin/gollum:22:in `load'
Nov 27 11:42:54 jeti100 gollum[40843]:         from /usr/bin/gollum:22:in `<main>'
Nov 27 11:42:54 jeti100 systemd[1]: gollum-wiki-server.service: Main process exited, code=exited, status=1/FAILURE
Nov 27 11:42:54 jeti100 systemd[1]: gollum-wiki-server.service: Failed with result 'exit-code'.
```

**Comment by deep-42-thought** [comment]
Or is this a problem of the ruby package itself?

**Comment by anatol** [comment]
It is a problem with `ruby-charlock_holmes` package. Current version available in `quarry` been compiled against old version of `icu` Arch package. The `icu` version has been moved up and the quarry package need to be rebuilt. Working on it.
