### ISSUE TITLE
ruby-gollum does not run w/o ruby-rdoc, but it's not a dependency

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#82]
I got the following error in my log, when trying to start gollum:
```
Feb 08 08:50:37 nlopc43 systemd[1]: Started Gollum Wiki Server.
Feb 08 08:50:37 nlopc43 gollum[4786]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- rdoc/markup/to_html (LoadError)
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/github-markup-1.7.0/lib/github/markup/rdoc.rb:3:in `<top (required)>'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/github-markup-1.7.0/lib/github/markups.rb:2:in `<module:Markup>'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `instance_eval'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:103:in `<module:Markup>'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:24:in `<module:GitHub>'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/github-markup-1.7.0/lib/github/markup.rb:10:in `<top (required)>'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-4.1.2/lib/gollum.rb:8:in `<top (required)>'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-4.1.2/bin/gollum:7:in `<top (required)>'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/bin/gollum:23:in `load'
Feb 08 08:50:37 nlopc43 gollum[4786]:         from /usr/bin/gollum:23:in `<main>'
Feb 08 08:50:37 nlopc43 systemd[1]: gollum.service: Main process exited, code=exited, status=1/FAILURE
Feb 08 08:50:37 nlopc43 systemd[1]: gollum.service: Failed with result 'exit-code'.
```
installing `ruby-rdoc` solved the issue for me. Maybe it should be added as a dependency somewhere?

**Comment by anatol** [comment]
I believe `rdoc` is **one** of markup backends. You don't really need it until use it. So it probably should be `optdepends=()`. Currently there are several optional backeds https://github.com/github/markup

Feel free to send a PR that lists all optdepends for this package.
