### ISSUE TITLE
libv8 fails to rebuild

### ISSUE THREAD

**Issue by eli-schwartz** [anatol/quarry#86]
```
==> Starting package()...
Building native extensions. This could take a while...
ERROR:  Error installing libv8-6.3.292.48.1.gem:
	ERROR: Failed to build gem native extension.

    current directory: /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/ext/libv8
/usr/bin/ruby -r ./siteconf20180227-650-1v7hfd.rb extconf.rb
creating Makefile
which: no python in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Traceback (most recent call last):
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 2679, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 2665, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 2420, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 1510, in RunOnDeps
    self.RunHooksRecursively(self._options, pm)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 1033, in RunHooksRecursively
    hook.run(self.root.root_dir)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 200, in run
    not gclient_eval.EvaluateCondition(self._condition, self._variables)):
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient_eval.py", line 319, in EvaluateCondition
    return _convert(main_node)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient_eval.py", line 279, in _convert
    left = _convert(node.values[0])
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient_eval.py", line 286, in _convert
    'invalid "and" operand %r (inside %r)' % (right, condition))
ValueError: invalid "and" operand 'checkout_arm' (inside '(checkout_linux and checkout_arm) and not build_for_node')
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 301, in <module>
    sys.exit(main())
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 296, in main
    return run(options, spec, root)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 290, in run
    return checkout.init()
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 133, in init
    self.run_gclient(*sync_cmd)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:117:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:115:in `chdir'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:115:in `setup_build_deps!'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:71:in `build_libv8!'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/gems/libv8-6.3.292.48.1 for inspection.
Results logged to /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0/libv8-6.3.292.48.1/gem_make.out
==> ERROR: A failure occurred in package().
```

**Comment by eli-schwartz** [comment]
Actually this is the same issue I mentioned at https://github.com/anatol/quarry/issues/85#issuecomment-366262693.
