### ISSUE TITLE
rebuild for icu-61 needed

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#89]
currently, e.g. gollum fails to start with:
```
Apr 07 08:23:47 jeti100 systemd[1]: Started Gollum Wiki Server.
Apr 07 08:23:47 jeti100 gollum[1302]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': libicuuc.so.60: cannot open shared object file: No such file or directory - /usr/lib/ruby/gems/2.5.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes/charlock_holmes.so (LoadError)
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/gems/2.5.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes.rb:1:in `<top (required)>'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/gems/2.5.0/gems/gitlab-grit-2.8.2/lib/grit.rb:79:in `<top (required)>'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter/git_layer_grit.rb:3:in `<top (required)>'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter.rb:1:in `<top (required)>'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-lib-4.2.7/lib/gollum-lib.rb:13:in `<top (required)>'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-4.1.2/lib/gollum/app.rb:4:in `<top (required)>'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-4.1.2/bin/gollum:242:in `<top (required)>'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/bin/gollum:23:in `load'
Apr 07 08:23:47 jeti100 gollum[1302]:         from /usr/bin/gollum:23:in `<main>'
Apr 07 08:23:47 jeti100 systemd[1]: gollum-wiki-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 07 08:23:47 jeti100 systemd[1]: gollum-wiki-server.service: Failed with result 'exit-code'.
```

I'm not sure, what exactly needs the rebuild, but I think, scrubbing through the packages with "objdump -x $pkg | grep NEEDED | grep libicuuc.so.60" might bring up more packages anyway.

**Comment by anatol** [comment]
Thank you. `charlock_holmes` package has been rebuilt.

Ideally quarry needs a tool that scans all native packages and checks that its *.so dependencies are up-to-date.
