### ISSUE TITLE
Gem request: asciidoctor-pdf and dependencies

### ISSUE THREAD

**Issue by InfernoZeus** [anatol/quarry#90]
I'm not sure how plausible this is, I think the dependency tree for `asciidoctor-pdf` is quite big, but would really appreciate it if it is possible. Without installing the Gem myself, I couldn't find a way to get the complete tree.

https://rubygems.org/gems/asciidoctor-pdf

**Comment by anatol** [comment]
Having this gem in `quarry` should be totally fine. One issue I see is that `asciidoctor-pdf` does not have any stable releases. For the last few years upstream released only `alpha` ones. Is there a chance to get upstream to release a stable version?

**Comment by anatol** [comment]
`asciidoctor-pdf` is published to rubygems. Please try it and let me know if the are any issues with the package.

The question about getting a stable release for the gem is still open.

**Comment by InfernoZeus** [comment]
@anatol I've just installed this package on a new system, and I'm now getting an error about missing themes:
```
$ asciidoctor-pdf --trace file.adoc
Traceback (most recent call last):
	16: from /usr/bin/asciidoctor-pdf:23:in `<main>'
	15: from /usr/bin/asciidoctor-pdf:23:in `load'
	14: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/bin/asciidoctor-pdf:31:in `<top (required)>'
	13: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
	12: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `each'
	11: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
	10: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `convert_file'
	 9: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `open'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `block in convert_file'
	 7: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1515:in `convert'
	 6: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1141:in `convert'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118:in `convert'
	 4: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:143:in `convert_document'
	 3: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:240:in `init_pdf'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/theme_loader.rb:73:in `load_theme'
	 1: from /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/theme_loader.rb:78:in `load_file'
/usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/theme_loader.rb:78:in `read': No such file or directory @ rb_sysopen - /usr/lib/ruby/gems/2.5.0/gems/asciidoctor-pdf-1.5.0.alpha.16/data/themes/default-theme.yml (Errno::ENOENT)
```

Do the `data` files need to be explicitly included, similar to what's needed for asciidoctor?

**Comment by anatol** [comment]
Yes, `asciidoctor-pdf` need to be updated as well. Looking at it right now.
