### ISSUE TITLE
something needs rebuild against new libicuuc.so.62

### ISSUE THREAD

**Issue by deep-42-thought** [anatol/quarry#96]
```
Aug 14 06:43:15 jeti100 systemd[1]: Started Gollum Wiki Server.
Aug 14 06:43:16 jeti100 gollum[1428]: /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': libicuuc.so.61: cannot open shared object file: No such file or directory - /usr/lib/ruby/gems/2.5.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes/charlock_holmes.so (LoadError)
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/gems/2.5.0/gems/charlock_holmes-0.7.6/lib/charlock_holmes.rb:1:in `<top (required)>'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/gems/2.5.0/gems/gitlab-grit-2.8.2/lib/grit.rb:79:in `<top (required)>'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter/git_layer_grit.rb:3:in `<top (required)>'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-grit_adapter-1.0.1/lib/grit_adapter.rb:1:in `<top (required)>'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-lib-4.2.7/lib/gollum-lib.rb:13:in `<top (required)>'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-4.1.2/lib/gollum/app.rb:4:in `<top (required)>'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/lib/ruby/gems/2.5.0/gems/gollum-4.1.2/bin/gollum:242:in `<top (required)>'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/bin/gollum:23:in `load'
Aug 14 06:43:16 jeti100 gollum[1428]:         from /usr/bin/gollum:23:in `<main>'
Aug 14 06:43:16 jeti100 systemd[1]: gollum-wiki-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 14 06:43:16 jeti100 systemd[1]: gollum-wiki-server.service: Failed with result 'exit-code'.
```
I'm not sure if this is ruby-gollum's or rubygem's fault. Please excuse if this has nothing to do with quarry.

Regards,
deep-42-thought

**Comment by anatol** [comment]
Thank you for the heads up. It actually gem `charlock_holmes` that depends on the old `libicuuc.so` and needs rebuild.

I rebuilt `libicuuc.so` and now it is in the repo. Please update your system.
